In [2]:
import pandas
target_df = pandas.read_csv('../data/model_data.csv')

In [3]:
target_df.head()

,Unnamed: 0,OWNER_CL_ID,ZIP_CD,GAS_RETAIL_CARD_USAGE_CD,MASTERCARD_USAGE_CD,VISA_CREDIT_CARD_USAGE_CD,COMMUNITY_CAUSES_CHARITY_CD,DOMESTIC_BUSINESS_TRAVEL_CD,INTERNET_BUY_CHNL_PRF_RNG_1_10,INCOME_THOUSANDS_B_VALUE_CD,...,ZIP_TOTAL_WAGES_SALARIES_TIPS_ETC,ZIP_TOTAL_WEALTH_INCOME,NUMBER_OF_RETURNS_IN_ZIP,num_policies,avg_prem,avg_fval,DESIRED_CL_CCPC,DESIRED_CL_CCPCEC,randnum,sample
0,1,10004700,89011,0,1,1,1.000000e+12,0,7.0,59.0,...,5.620412e+05,81441.231,12681,1,250.651598,250000.0,0,0,0.031078,holdout
1,2,10005cd7,92307,0,0,0,0.000000e+00,0,2.0,49.0,...,6.207945e+05,26645.893,16153,1,531.553054,250000.0,0,0,0.876781,training
2,3,1000a8f6,78550,0,1,0,1.001010e+12,0,7.0,34.0,...,6.752293e+05,27608.343,21558,2,445.027966,20000.0,0,0,0.831547,training
3,4,1000b62a,91789,0,0,0,0.000000e+00,0,8.0,65.0,...,1.207591e+06,326413.912,21076,1,40797.770756,310000.0,1,1,0.838566,training
4,5,1000cbcd,78635,0,0,0,0.000000e+00,0,7.0,64.0,...,6.191220e+02,114.496,47,1,1722.667787,1000000.0,0,1,0.330509,training

In [4]:
len(target_df)

250374

In [11]:
import numpy as np

target_df["total_premium"] = target_df['avg_prem'] * target_df['num_policies']

In [12]:

target_df.head()

,Unnamed: 0,OWNER_CL_ID,ZIP_CD,GAS_RETAIL_CARD_USAGE_CD,MASTERCARD_USAGE_CD,VISA_CREDIT_CARD_USAGE_CD,COMMUNITY_CAUSES_CHARITY_CD,DOMESTIC_BUSINESS_TRAVEL_CD,INTERNET_BUY_CHNL_PRF_RNG_1_10,INCOME_THOUSANDS_B_VALUE_CD,...,ZIP_TOTAL_WEALTH_INCOME,NUMBER_OF_RETURNS_IN_ZIP,num_policies,avg_prem,avg_fval,DESIRED_CL_CCPC,DESIRED_CL_CCPCEC,randnum,sample,total_premium
0,1,10004700,89011,0,1,1,1.000000e+12,0,7.0,59.0,...,81441.231,12681,1,250.651598,250000.0,0,0,0.031078,holdout,250.651598
1,2,10005cd7,92307,0,0,0,0.000000e+00,0,2.0,49.0,...,26645.893,16153,1,531.553054,250000.0,0,0,0.876781,training,531.553054
2,3,1000a8f6,78550,0,1,0,1.001010e+12,0,7.0,34.0,...,27608.343,21558,2,445.027966,20000.0,0,0,0.831547,training,890.055932
3,4,1000b62a,91789,0,0,0,0.000000e+00,0,8.0,65.0,...,326413.912,21076,1,40797.770756,310000.0,1,1,0.838566,training,40797.770756
4,5,1000cbcd,78635,0,0,0,0.000000e+00,0,7.0,64.0,...,114.496,47,1,1722.667787,1000000.0,0,1,0.330509,training,1722.667787

In [26]:
target_df.to_csv('../output/target_predictions.csv')

In [29]:
target_df.describe()

,Unnamed: 0,ZIP_CD,GAS_RETAIL_CARD_USAGE_CD,MASTERCARD_USAGE_CD,VISA_CREDIT_CARD_USAGE_CD,COMMUNITY_CAUSES_CHARITY_CD,DOMESTIC_BUSINESS_TRAVEL_CD,INTERNET_BUY_CHNL_PRF_RNG_1_10,INCOME_THOUSANDS_B_VALUE_CD,DISCRET_SPEND_DOLLARS_B_CD,...,ZIP_TOTAL_WAGES_SALARIES_TIPS_ETC,ZIP_TOTAL_WEALTH_INCOME,NUMBER_OF_RETURNS_IN_ZIP,num_policies,avg_prem,avg_fval,DESIRED_CL_CCPC,DESIRED_CL_CCPCEC,randnum,total_premium
count,250374.000000,250374.000000,250374.000000,250374.000000,250374.000000,2.503740e+05,250374.000000,217668.000000,250343.000000,250343.000000,...,2.503740e+05,2.503740e+05,250374.000000,250374.000000,2.492560e+05,250336.000000,250374.000000,250374.000000,250374.000000,2.492560e+05
mean,125187.500000,46302.981803,0.322406,0.455059,0.537077,2.663003e+11,0.248153,4.742966,86.938397,11979.042398,...,9.093272e+05,1.110011e+05,18174.326787,1.362590,1.794422e+03,272063.653293,0.062622,0.176316,0.500379,2.259545e+03
std,72276.892486,33617.708289,1.595716,1.929879,1.955580,4.454837e+11,1.556765,2.701515,65.801297,10566.265480,...,7.006132e+05,3.179211e+05,11301.528592,0.746111,6.610425e+03,276713.393341,0.242283,0.381090,0.288609,7.270233e+03
min,1.000000,1001.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,1.000000,2.000000,888.000000,...,0.000000e+00,0.000000e+00,0.000000,0.000000,2.056158e+00,0.000000,0.000000,0.000000,0.000006,2.056158e+00
25%,62594.250000,11550.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,2.000000,45.000000,5669.000000,...,4.527688e+05,1.768187e+04,9998.000000,1.000000,4.101143e+02,100000.000000,0.000000,0.000000,0.250332,4.983481e+02
50%,125187.500000,35756.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,4.000000,70.000000,9892.000000,...,7.854096e+05,4.573923e+04,16630.000000,1.000000,7.839932e+02,175000.000000,0.000000,0.000000,0.500543,1.028176e+03
75%,187780.750000,78660.000000,0.000000,0.000000,0.000000,1.000000e+12,0.000000,7.000000,110.000000,15801.000000,...,1.193794e+06,1.025387e+05,24332.000000,2.000000,1.644979e+03,350000.000000,0.000000,0.000000,0.750643,2.163816e+03
max,250374.000000,99929.000000,11.000000,11.000000,11.000000,1.111111e+12,11.000000,10.000000,4735.000000,728473.000000,...,6.999739e+06,1.408856e+07,60337.000000,13.000000,1.222473e+06,1000000.000000,1.000000,1.000000,0.999999,1.222473e+06